<?php /** @var \Magento\Framework\View\Element\Template $block */ ?>
<div>
    <p><?= __('Full name: '), $block->escapeHtml($block->getData('first_name') . ' ' . $block->getData('second_name')) ?></p>
    <p><?= __('Repository URL: ') ?>
        <a href="<?= $block->escapeUrl($block->getData('repository_url')) ?>">
            <?= $block->escapeHtml($block->getData('repository_url')) ?>
        </a>
    </p>
</div>
