<?php /** @var \Magento\Framework\View\Element\Template $block */ ?>
<div class="button-open-chat-header">
    <a href="javascript:void(0);"
       class="button-open-chat-header__link"
       data-mage-init='{"alexeybChatButtonOpen": {
       "hideButton": "false"
       }}'
    >
        <img class="button-open-chat-header__img"
             src="<?= $block->getViewFileUrl("Alexeyb_Chat::images/twodialogueboxessymbol_120591.svg") ?>"
             alt="<?= $block->escapeHtml(__('Chat')) ?>">
    </a>
</div>